version: '3.8'

services:
  parquimetro-service:
    image: parquimetro-service:latest
    container_name: parquimetro-service
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/parquimetro
    depends_on:
      - mongo
    networks:
      - app_network

  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app_network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin123
      - MONGO_INITDB_DATABASE=parquimetro

volumes:
  mongo_data:

networks:
  app_network:
